import { router } from 'expo-router';
import { Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { PracticeRow, usePracticeList } from '~/entity/practice';

export default function PracticeView() {
  const items = usePracticeList();
  const completed = items.filter((item) => item.status === 'done').length;

  // ponytail: typed routes are generated by Expo at dev-server start; keep this
  // route usable before that generated file exists.
  const handlePress = (id: (typeof items)[number]['id']) =>
    router.push(
      (id === 'kiosk'
        ? '/practice-kiosk'
        : id === 'sms'
          ? '/practice-sms'
          : `/practice/${id}`) as never
    );

  return (
    <SafeAreaView className="flex-1 bg-cream">
      <View className="px-7 pt-8">
        <Text className="text-lg font-bold text-ink-soft">오늘의 연습</Text>
        <Text className="mt-1 text-3xl font-extrabold text-ink">하나씩 천천히 해봐요</Text>
        <View className="mt-5 rounded-2xl bg-brand-light px-5 py-4">
          <Text className="text-base font-bold text-brand-dark">
            완료한 연습 {completed}개 · 다음 연습은 한 가지만 열려요
          </Text>
        </View>
      </View>

      <View className="gap-6 px-7 pt-8">
        {items.map((item) => (
          <PracticeRow
            key={item.id}
            title={item.title}
            note={item.note}
            icon={item.icon}
            status={item.status}
            onPress={() => handlePress(item.id)}
          />
        ))}
      </View>
    </SafeAreaView>
  );
}
